### ISSUE TITLE
Latest release fails to install

### ISSUE THREAD

**Issue by PSJMcNeill** [npes87184/ScreenShareTile#8]
Currently running a Pixel Experience Android 12 Rom.

Installing 1.3.0 version works but if I try the latest version or the play store version I get can't parse apk or play store error of can't install.

**Comment by npes87184** [comment]
I can reproduce this problem, I will dig on it when I have free time (usually in weekend time)

Thank you for your report.

**Comment by npes87184** [comment]
Hi @PSJMcNeill 

I have fixed this issue by commit 154661595d267f345260615cd03e00a5e9255fa2.

I also release [v1.4.1](https://github.com/npes87184/ScreenShareTile/releases/tag/v1.4.1) for this issue.

Please install new version to solve this problem.

Thank you for your report.

Best regards.
